### ISSUE TITLE
Error in retry

### ISSUE THREAD

**Issue by autarchprinceps** [troyready/sensu-transport-snssqs-ng#6]
I get the following error in the retry addition, after updating to 2.2.0

/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/retries-0.0.5/lib/retries.rb:35:in `with_retries': Error with options to with_retries: :base_sleep_seconds cannot be greater than :max_sleep_seconds. (RuntimeError)
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-snssqs-ng-2.2.0/lib/sensu/transport/snssqs.rb:164:in `send_message'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-snssqs-ng-2.2.0/lib/sensu/transport/snssqs.rb:147:in `block in publish'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'

**Comment by troyready** [comment]
Sorry for not catching this, and thanks for the fix! Released as v2.2.1
